In [1]:
import pandas as pd

In [3]:
data={'Name':['Alice','Bob'],'Age':[25,30]}
df=pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [4]:
lst=[['Alice',25],['Bob',30]]
df=pd.DataFrame(lst,columns=['Name','Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [9]:
df.head()
df.tail()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 172.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [12]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [13]:
df['Age']

0    25
1    30
Name: Age, dtype: int64

In [14]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [18]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [21]:
df.iloc[1,0]

'Bob'

In [23]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [24]:
df['Gender']=['F','M']
df

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [25]:
df.drop('Age',axis=1,inplace=True)

In [26]:
df

    Name Gender
0  Alice      F
1    Bob      M

In [38]:
df.isnull()

    Name  Gender
0  False    True
1  False   False

In [39]:
df.dropna()

  Name Gender
1  Bob      M

In [40]:
df.fillna(0)

    Name Gender
0  Alice      0
1    Bob      M

In [42]:
df.loc[2]=['Kuttu','M']

In [45]:
df.loc[3]=['Amal',None]

In [48]:
df['Age']=[25,30,35,40]

In [50]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    32.5
Name: Age, dtype: float64

In [57]:
data2=[[1001,'ECE',1],[1002,'CIVIL',2]]
df2=pd.DataFrame(data2,columns=['DeptID','DeptName','key'])

In [59]:
df['key']=[1,2,1,2]
df

    Name Gender  Age  key
0  Alice      F   25    1
1    Bob      M   30    2
2  Kuttu      M   35    1
3   Amal    NaN   40    2

In [61]:
pd.merge(df,df2,on='key')

    Name Gender  Age  key  DeptID DeptName
0  Alice      F   25    1    1001      ECE
1    Bob      M   30    2    1002    CIVIL
2  Kuttu      M   35    1    1001      ECE
3   Amal    NaN   40    2    1002    CIVIL

In [65]:
df1 = df.set_index("key")
df2 = df2.set_index("key")
df1.join(df2)

      Name Gender  Age  DeptID DeptName
key
1    Alice      F   25    1001      ECE
2      Bob      M   30    1002    CIVIL
1    Kuttu      M   35    1001      ECE
2     Amal    NaN   40    1002    CIVIL

In [72]:
df.to_csv('output.csv',index=False)

In [78]:
df3=pd.read_csv('libraries/employee.csv')

   Name  Age Gender
0   Aby   25      M
1  Biby   35      M
2  Siby   32      M
3  Tiby   27      M

In [79]:
df3.sort_values('Age')

   Name  Age Gender
0   Aby   25      M
3  Tiby   27      M
2  Siby   32      M
1  Biby   35      M

In [80]:
df['Age'].apply(lambda x:x+1)

0    26
1    31
2    36
3    41
Name: Age, dtype: int64

In [81]:
df['Name'].unique()

<ArrowStringArray>
['Alice', 'Bob', 'Kuttu', 'Amal']
Length: 4, dtype: str

In [82]:
df['Age'].value_counts()

Age
25    1
30    1
35    1
40    1
Name: count, dtype: int64